
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 02 18:57:27 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int LT = 13;
  public static final int OVER = 12;
  public static final int ELSE = 3;
  public static final int NOTEQ = 19;
  public static final int PLUS = 9;
  public static final int RPAREN = 23;
  public static final int INT = 5;
  public static final int SEMI = 20;
  public static final int WHILE = 7;
  public static final int RETURN = 4;
  public static final int ERROR = 29;
  public static final int RWAVEPAREN = 28;
  public static final int LWAVEPAREN = 27;
  public static final int LBOXPAREN = 25;
  public static final int IF = 2;
  public static final int LPAREN = 22;
  public static final int GT = 14;
  public static final int ID = 24;
  public static final int NUM = 8;
  public static final int COMMA = 21;
  public static final int LTEQ = 15;
  public static final int EOF = 0;
  public static final int MINUS = 10;
  public static final int RBOXPAREN = 26;
  public static final int error = 1;
  public static final int EQ = 17;
  public static final int GTEQ = 16;
  public static final int EQEQ = 18;
  public static final int VOID = 6;
}

